services:
    app.media_repository:
        class: AppBundle\Repository\MediaRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['AppBundle\Entity\Media']
        lazy: true

    app.vote_repository:
        class: AppBundle\Repository\VoteRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['AppBundle\Entity\Vote']
        lazy: true
